name: Run Cypress tests

on: [push, pull_request]

jobs:
  cypress_tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Run Cypress
        uses: cypress-io/github-action@v2
        with:
          build: yarn build
          start: yarn pre-cypress
          browser: chrome
          headless: true
          
      - name: Cypress screenshots
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Cypress videos
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
