name: Tweet release

on: 
  release:
    types: [published]

jobs:
  tweet-release:
    runs-on: ubuntu-latest

    steps:
      - uses: ethomson/send-tweet-action@v1
        with:
          status: >
            ✨ I've just released ${{ github.event.release.tag_name }} of Spruce, the global state management library for Alpine.js.


            Check out the release notes here: https://github.com/ryangjchandler/spruce/releases/tag/${{ github.event.release.tag_name }}
          consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
